-- MySQL Script generated by MySQL Workbench
-- 11/02/16 19:39:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profesores` (
  `idProfesores` INT NOT NULL,
  `nombre_profesor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idProfesores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cursos` (
  `idCurso` INT NOT NULL,
  `nombre_curso` VARCHAR(50) NULL,
  `fk_idProfesores` INT NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `fk_Cursos_Profesores1_idx` (`fk_idProfesores` ASC),
  CONSTRAINT `fk_Cursos_Profesores1`
    FOREIGN KEY (`fk_idProfesores`)
    REFERENCES `mydb`.`Profesores` (`idProfesores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo_Proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo_Proyecto` (
  `idTipo_Proyecto` INT NOT NULL,
  `nombre_tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipo_Proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proyectos` (
  `idProyecto` INT NOT NULL,
  `descripcion_proyecto` VARCHAR(200) NULL,
  `resumen_proyecto` VARCHAR(200) NULL,
  `duracion_proyecto` VARCHAR(50) NULL,
  `fk_Proyecto_idTipo_Proyecto` INT NOT NULL,
  `fk_idCursos` INT NOT NULL,
  PRIMARY KEY (`idProyecto`),
  INDEX `fk_Proyectos_Tipo_Proyecto_idx` (`fk_Proyecto_idTipo_Proyecto` ASC),
  INDEX `fk_Proyectos_Cursos1_idx` (`fk_idCursos` ASC),
  CONSTRAINT `fk_Proyectos_Tipo_Proyecto`
    FOREIGN KEY (`fk_Proyecto_idTipo_Proyecto`)
    REFERENCES `mydb`.`Tipo_Proyecto` (`idTipo_Proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyectos_Cursos1`
    FOREIGN KEY (`fk_idCursos`)
    REFERENCES `mydb`.`Cursos` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tecnologias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tecnologias` (
  `idTecnologias` INT NOT NULL,
  `nombre_tecnologia` VARCHAR(50) NULL,
  `fk_idProyectos` INT NOT NULL,
  PRIMARY KEY (`idTecnologias`),
  INDEX `fk_Tecnologias_Proyectos1_idx` (`fk_idProyectos` ASC),
  CONSTRAINT `fk_Tecnologias_Proyectos1`
    FOREIGN KEY (`fk_idProyectos`)
    REFERENCES `mydb`.`Proyectos` (`idProyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Semestre` (
  `idSemestre` INT NOT NULL,
  `anno_semestre` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSemestre`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
